export const mockOrders = [
  {
    id: 'ORD-2024-001',
    user_name:    'Amina Johnson',
    user_email:   'amina@example.co.tz',
    plan_id:      1,
    plan_title:   'Villa Serena',
    total_amount: 1_400_000,
    payment_status:  'paid',
    payment_method:  'M-Pesa',
    created_at:   '2024-01-15T10:30:00Z',
  },
  {
    id: 'ORD-2024-002',
    user_name:    'Mohamed Salim',
    user_email:   'msalim@example.co.tz',
    plan_id:      2,
    plan_title:   'Nyumba Ndoto',
    total_amount:   680_000,
    payment_status:  'paid',
    payment_method:  'Tigo Pesa',
    created_at:   '2024-03-22T14:22:00Z',
  },
  {
    id: 'ORD-2024-003',
    user_name:    'Grace Wanjiru',
    user_email:   'grace@example.co.tz',
    plan_id:      5,
    plan_title:   'Nakshi Compact',
    total_amount:   350_000,
    payment_status:  'pending',
    payment_method:  'Airtel Money',
    created_at:   '2024-06-01T09:15:00Z',
  },
  {
    id: 'ORD-2024-004',
    user_name:    'David Mwangi',
    user_email:   'david@example.co.tz',
    plan_id:      4,
    plan_title:   'Jumba la Lux',
    total_amount: 2_200_000,
    payment_status:  'paid',
    payment_method:  'Halo Pesa',
    created_at:   '2024-05-10T16:45:00Z',
  },
  {
    id: 'ORD-2024-005',
    user_name:    'Fatuma Hassan',
    user_email:   'fatuma@example.co.tz',
    plan_id:      3,
    plan_title:   'Bungalow Amani',
    total_amount:   520_000,
    payment_status:  'failed',
    payment_method:  'M-Pesa',
    created_at:   '2024-04-05T11:00:00Z',
  },
  {
    id: 'ORD-2024-006',
    user_name:    'Peter Makonde',
    user_email:   'pmakonde@example.co.tz',
    plan_id:      6,
    plan_title:   'Palazzo Classic',
    total_amount: 1_750_000,
    payment_status:  'paid',
    payment_method:  'Tigo Pesa',
    created_at:   '2024-02-28T08:30:00Z',
  },
  {
    id: 'ORD-2024-007',
    user_name:    'Sarah Kimani',
    user_email:   'sarah@example.co.tz',
    plan_id:      7,
    plan_title:   'Nyumba ya Bahari',
    total_amount:   890_000,
    payment_status:  'pending',
    payment_method:  'Airtel Money',
    created_at:   '2024-06-05T13:20:00Z',
  },
  {
    id: 'ORD-2024-008',
    user_name:    'James Odhiambo',
    user_email:   'james@example.co.tz',
    plan_id:      8,
    plan_title:   'Duplex Imara',
    total_amount: 1_100_000,
    payment_status:  'paid',
    payment_method:  'M-Pesa',
    created_at:   '2024-03-15T09:45:00Z',
  },
]
